---
- name: deploy hello world application
  hosts: host
  remote_user: dyuan
  tasks:
  - name: COPY FILE
    copy:
      src: ../build/libs/ansible-demo-0.0.1-SNAPSHOT.jar
      dest: ~/
  - name: KILL PREVIOUS JAR
    shell: kill $(lsof -t -i :8080) || true
  - name: START JAR
    shell: nohup java -jar ~/ansible-demo-0.0.1-SNAPSHOT.jar > ~/log &
  - name: WAIT FOR STARTING UP
    shell: echo 1
  - name: SPEAK DEPLOY DONE!
    say:
      msg: "Deploy Done!"